window.dockerSwarmCommands = [
    { command: 'docker swarm init', description: 'Initializes a new Docker Swarm cluster' },
    { command: 'docker swarm join --token <token> <manager-ip>:<port>', description: 'Joins a node to a Swarm as a worker' },
    { command: 'docker swarm join-token worker', description: 'Displays the join token for workers' },
    { command: 'docker swarm join-token manager', description: 'Displays the join token for managers' },
    { command: 'docker node ls', description: 'Lists all nodes in the Swarm' },
    { command: 'docker node update --availability <availability> <node-id>', description: 'Updates the availability of a node' },
    { command: 'docker service create --name <service_name> <image>', description: 'Creates a new service in the Swarm' },
    { command: 'docker service ls', description: 'Lists all services in the Swarm' },
    { command: 'docker service inspect <service_name>', description: 'Displays detailed information about a service' },
    { command: 'docker service update --image <new_image> <service_name>', description: 'Updates the image of a service' },
    { command: 'docker service scale <service_name>=<replica_count>', description: 'Scales a service to the specified number of replicas' },
    { command: 'docker service rm <service_name>', description: 'Removes a service from the Swarm' },
    { command: 'docker stack deploy -c <compose-file> <stack_name>', description: 'Deploys a new stack or updates an existing stack' },
    { command: 'docker stack ls', description: 'Lists all stacks in the Swarm' },
    { command: 'docker stack services <stack_name>', description: 'Lists all services in a stack' },
    { command: 'docker stack ps <stack_name>', description: 'Lists all tasks in a stack' },
    { command: 'docker stack rm <stack_name>', description: 'Removes a stack from the Swarm' },
    { command: 'docker config ls', description: 'Lists all configs in the Swarm' },
    { command: 'docker config create <config_name> <config_file>', description: 'Creates a new config in the Swarm' },
    { command: 'docker config rm <config_name>', description: 'Removes a config from the Swarm' },
    { command: 'docker secret ls', description: 'Lists all secrets in the Swarm' },
    { command: 'docker secret create <secret_name> <secret_file>', description: 'Creates a new secret in the Swarm' },
    { command: 'docker secret rm <secret_name>', description: 'Removes a secret from the Swarm' },
    { command: 'docker swarm leave', description: 'Makes a node leave the Swarm' },
    { command: 'docker swarm leave --force', description: 'Forces a node to leave the Swarm, even if it is a manager' },
    { command: 'docker info', description: 'Displays detailed information about the Docker installation, including Swarm status' }
];
