window.dockerCommands = [
    { command: 'docker --version', description: 'Displays Docker version information' },
    { command: 'docker ps', description: 'Lists running containers' },
    { command: 'docker ps -a', description: 'Lists all containers (including stopped ones)' },
    { command: 'docker images', description: 'Lists all Docker images on the system' },
    { command: 'docker pull <image_name>', description: 'Downloads a Docker image from Docker Hub' },
    { command: 'docker run <image_name>', description: 'Runs a container from the specified image' },
    { command: 'docker run -d <image_name>', description: 'Runs a container in detached mode (in the background)' },
    { command: 'docker run -it <image_name> /bin/bash', description: 'Runs a container interactively with a bash shell' },
    { command: 'docker start <container_id>', description: 'Starts a stopped container' },
    { command: 'docker stop <container_id>', description: 'Stops a running container' },
    { command: 'docker restart <container_id>', description: 'Restarts a running container' },
    { command: 'docker rm <container_id>', description: 'Removes a stopped container' },
    { command: 'docker rmi <image_name>', description: 'Removes an image' },
    { command: 'docker logs <container_id>', description: 'Shows logs from a specific container' },
    { command: 'docker exec -it <container_id> /bin/bash', description: 'Executes a command inside a running container' },
    { command: 'docker build -t <image_name> .', description: 'Builds a Docker image from a Dockerfile' },
    { command: 'docker-compose up', description: 'Starts services defined in a docker-compose.yml file' },
    { command: 'docker-compose down', description: 'Stops and removes containers, networks, and volumes defined in docker-compose.yml' },
    { command: 'docker network ls', description: 'Lists all Docker networks' },
    { command: 'docker network create <network_name>', description: 'Creates a new Docker network' },
    { command: 'docker volume ls', description: 'Lists all Docker volumes' },
    { command: 'docker volume create <volume_name>', description: 'Creates a new Docker volume' },
    { command: 'docker inspect <container_id>', description: 'Displays detailed information about a container' },
    { command: 'docker stats', description: 'Shows real-time stats of running containers (CPU, memory usage, etc.)' },
    { command: 'docker commit <container_id> <new_image_name>', description: 'Creates a new image from a container’s changes' },
    { command: 'docker tag <source_image> <target_image>', description: 'Tags an image for pushing to a repository' },
    { command: 'docker push <repository_name>', description: 'Pushes an image to Docker Hub or a registry' },
    { command: 'docker pull <repository_name>', description: 'Pulls an image from Docker Hub or a registry' },
    { command: 'docker login', description: 'Logs in to a Docker registry' },
    { command: 'docker logout', description: 'Logs out from a Docker registry' },
    { command: 'docker prune -f', description: 'Removes all stopped containers, unused networks, and dangling images' }
];
