window.gitCommands = [
    { command: 'git init', description: 'Initializes a new Git repository' },
    { command: 'git clone <repo-url>', description: 'Clones an existing repository from a remote location' },
    { command: 'git status', description: 'Displays the current status of the working directory' },
    { command: 'git add <file>', description: 'Adds a file to the staging area' },
    { command: 'git commit -m "<message>"', description: 'Commits the staged changes with a message' },
    { command: 'git push', description: 'Pushes the committed changes to a remote repository' },
    { command: 'git pull', description: 'Fetches and merges changes from the remote repository' },
    { command: 'git branch', description: 'Lists all local branches' },
    { command: 'git branch <branch-name>', description: 'Creates a new branch' },
    { command: 'git checkout <branch>', description: 'Switches to the specified branch' },
    { command: 'git merge <branch>', description: 'Merges the specified branch into the current branch' },
    { command: 'git stash', description: 'Temporarily saves uncommitted changes' },
    { command: 'git stash pop', description: 'Restores the stashed changes' },
    { command: 'git log', description: 'Displays the commit history' },
    { command: 'git reset --hard <commit>', description: 'Resets the working directory and index to the specified commit' },
    { command: 'git rebase <branch>', description: 'Reapplies commits on top of another base tip' },
    { command: 'git remote -v', description: 'Shows remote repository URLs' },
    { command: 'git fetch', description: 'Fetches the latest changes without merging' },
    { command: 'git diff', description: 'Displays changes between commits, branches, or the working directory' },
    { command: 'git tag <tag-name>', description: 'Creates a new tag' },
    { command: 'git rm <file>', description: 'Removes a file from the repository' },
    { command: 'git checkout <commit> -- <file>', description: 'Restores a specific file to a previous commit state' }
];
