window.htmlCommands = [
    { command: '<!DOCTYPE html>', description: 'Defines the document type' },
    { command: '<html>', description: 'Root element of an HTML document' },
    { command: '<head>', description: 'Contains meta-information about the document' },
    { command: '<title>', description: 'Defines the title of the document' },
    { command: '<meta charset="UTF-8">', description: 'Defines the character encoding for the document' },
    { command: '<link rel="stylesheet" href="styles.css">', description: 'Links an external CSS file' },
    { command: '<script src="script.js"></script>', description: 'Links an external JavaScript file' },
    { command: '<body>', description: 'Defines the main content of the document' },
    { command: '<h1> to <h6>', description: 'Defines HTML headings, <h1> is the highest level' },
    { command: '<p>', description: 'Defines a paragraph' },
    { command: '<a href="url">link</a>', description: 'Defines a hyperlink' },
    { command: '<img src="image.jpg" alt="description">', description: 'Defines an image' },
    { command: '<ul>', description: 'Defines an unordered (bulleted) list' },
    { command: '<ol>', description: 'Defines an ordered (numbered) list' },
    { command: '<li>', description: 'Defines a list item' },
    { command: '<table>', description: 'Defines a table' },
    { command: '<tr>', description: 'Defines a row in a table' },
    { command: '<td>', description: 'Defines a cell in a table' },
    { command: '<th>', description: 'Defines a header cell in a table' },
    { command: '<form>', description: 'Defines an HTML form for user input' },
    { command: '<input type="text">', description: 'Defines an input control' },
    { command: '<textarea>', description: 'Defines a multiline text input control' },
    { command: '<button>', description: 'Defines a clickable button' },
    { command: '<label>', description: 'Defines a label for an <input> element' },
    { command: '<select>', description: 'Defines a drop-down list' },
    { command: '<option>', description: 'Defines options in a drop-down list' },
    { command: '<div>', description: 'Defines a division or section in the document' },
    { command: '<span>', description: 'Defines a section in a document' },
    { command: '<header>', description: 'Defines a header for a document or section' },
    { command: '<footer>', description: 'Defines a footer for a document or section' },
    { command: '<nav>', description: 'Defines navigation links' },
    { command: '<article>', description: 'Defines an article' },
    { command: '<section>', description: 'Defines a section in a document' },
    { command: '<aside>', description: 'Defines content aside from the content it is placed in' },
    { command: '<main>', description: 'Defines the main content of the document' },
    { command: '<figure>', description: 'Defines self-contained content' },
    { command: '<figcaption>', description: 'Defines a caption for a <figure> element' }
];
