window.linuxCommands = [
    { command: 'ls', description: 'Lists the files and directories in the current directory' },
    { command: 'cd <directory>', description: 'Changes the current directory to the specified one' },
    { command: 'pwd', description: 'Prints the current working directory' },
    { command: 'mkdir <directory_name>', description: 'Creates a new directory' },
    { command: 'rmdir <directory_name>', description: 'Removes an empty directory' },
    { command: 'rm <file>', description: 'Removes a file' },
    { command: 'rm -r <directory>', description: 'Removes a directory and its contents' },
    { command: 'cp <source> <destination>', description: 'Copies a file or directory' },
    { command: 'mv <source> <destination>', description: 'Moves or renames a file or directory' },
    { command: 'cat <file>', description: 'Displays the contents of a file' },
    { command: 'more <file>', description: 'Views file content page by page' },
    { command: 'less <file>', description: 'Similar to more, but allows backward navigation' },
    { command: 'head <file>', description: 'Displays the first 10 lines of a file' },
    { command: 'tail <file>', description: 'Displays the last 10 lines of a file' },
    { command: 'touch <file>', description: 'Creates an empty file or updates the timestamp of an existing file' },
    { command: 'chmod <permissions> <file>', description: 'Changes the permissions of a file or directory' },
    { command: 'chown <owner>:<group> <file>', description: 'Changes the owner and group of a file or directory' },
    { command: 'ps', description: 'Displays a list of currently running processes' },
    { command: 'top', description: 'Shows real-time information about running processes' },
    { command: 'kill <PID>', description: 'Terminates a process by its PID' },
    { command: 'df -h', description: 'Shows disk space usage in human-readable format' },
    { command: 'du -h <directory>', description: 'Shows the disk usage of a directory in human-readable format' },
    { command: 'tar -cvf <archive.tar> <files>', description: 'Creates a tar archive from the specified files' },
    { command: 'tar -xvf <archive.tar>', description: 'Extracts files from a tar archive' },
    { command: 'gzip <file>', description: 'Compresses a file using gzip' },
    { command: 'gunzip <file.gz>', description: 'Decompresses a gzipped file' },
    { command: 'find <directory> -name <file_name>', description: 'Searches for files and directories by name' },
    { command: 'grep <pattern> <file>', description: 'Searches for a specific pattern in a file' },
    { command: 'echo <text>', description: 'Displays a line of text in the terminal' },
    { command: 'sudo <command>', description: 'Executes a command as a superuser' },
    { command: 'apt-get update', description: 'Updates the package list (Debian-based systems)' },
    { command: 'apt-get upgrade', description: 'Upgrades all installed packages to the latest version (Debian-based systems)' },
    { command: 'yum update', description: 'Updates the package list (Red Hat-based systems)' },
    { command: 'yum install <package>', description: 'Installs a package (Red Hat-based systems)' },
    { command: 'df -h', description: 'Displays disk space usage in human-readable format' },
    { command: 'ifconfig', description: 'Displays network configuration' },
    { command: 'ping <host>', description: 'Checks connectivity to a host' },
    { command: 'wget <url>', description: 'Downloads files from the web' },
    { command: 'curl <url>', description: 'Transfers data from or to a server using a URL' },
    { command: 'whoami', description: 'Displays the current logged-in user' },
    { command: 'history', description: 'Shows the command history' },
    { command: 'alias', description: 'Creates a shortcut for a command' },
    { command: 'reboot', description: 'Reboots the system' },
    { command: 'shutdown now', description: 'Shuts down the system immediately' },
    { command: 'man <command>', description: 'Displays the manual page for a command' }
];
