window.networkingCommands = [
    { command: 'ping <hostname_or_ip>', description: 'Sends ICMP echo requests to test connectivity with a host' },
    { command: 'traceroute <hostname_or_ip>', description: 'Traces the path packets take to reach a network host' },
    { command: 'ifconfig', description: 'Displays or configures network interfaces (deprecated, use `ip`)' },
    { command: 'ip addr show', description: 'Shows IP addresses assigned to network interfaces' },
    { command: 'ip link show', description: 'Displays the status of network interfaces' },
    { command: 'ip route show', description: 'Displays or configures routing table information' },
    { command: 'ip neigh', description: 'Displays neighbor (ARP) table' },
    { command: 'netstat -i', description: 'Displays network interface statistics' },
    { command: 'netstat -r', description: 'Displays the routing table' },
    { command: 'netstat -anp', description: 'Displays active connections and listening ports with associated processes' },
    { command: 'ss -tuln', description: 'Displays open TCP and UDP ports and their listening status' },
    { command: 'nslookup <domain>', description: 'Queries DNS to obtain domain name or IP address mapping' },
    { command: 'dig <domain>', description: 'Queries DNS servers for detailed information about domain records' },
    { command: 'host <domain>', description: 'Performs DNS lookups and returns a simple result' },
    { command: 'nmap <target>', description: 'Performs network discovery and security auditing (port scanning)' },
    { command: 'tcpdump', description: 'Captures and analyzes network packets' },
    { command: 'curl <url>', description: 'Transfers data from or to a server, using supported protocols like HTTP' },
    { command: 'wget <url>', description: 'Downloads files from the web via HTTP, HTTPS, or FTP' },
    { command: 'scp <source> <destination>', description: 'Securely copies files between hosts over SSH' },
    { command: 'ssh <user>@<host>', description: 'Connects to a remote host using SSH' },
    { command: 'nc -zv <host> <port>', description: 'Checks if a port on a remote host is open (using netcat)' },
    { command: 'nmcli', description: 'Command-line tool for managing NetworkManager, useful for configuring networks' },
    { command: 'systemctl restart network', description: 'Restarts network services on the system' },
    { command: 'hostname', description: 'Displays or sets the hostname of the system' },
    { command: 'route -n', description: 'Displays the kernel routing table' },
    { command: 'iptables -L', description: 'Displays firewall rules (iptables)' },
    { command: 'ufw status', description: 'Displays the status of the Uncomplicated Firewall (UFW)' },
    { command: 'ufw allow <port>', description: 'Allows traffic on a specified port (with UFW)' },
    { command: 'ufw enable', description: 'Enables the UFW firewall' },
    { command: 'ethtool <interface>', description: 'Displays or modifies network interface parameters (e.g., speed, duplex)' },
    { command: 'whois <domain>', description: 'Displays information about domain registration' },
    { command: 'mtr <hostname_or_ip>', description: 'Combines ping and traceroute for real-time network diagnostics' },
    { command: 'arp -a', description: 'Displays the ARP table for network mapping of IP to MAC addresses' },
    { command: 'hostnamectl', description: 'Manages the system’s hostname' },
    { command: 'iwconfig', description: 'Displays or configures wireless network interfaces (deprecated, use `iw`)' },
    { command: 'iwlist <interface> scan', description: 'Scans for available wireless networks' },
    { command: 'dhclient', description: 'Requests an IP address from a DHCP server' },
    { command: 'firewall-cmd --list-all', description: 'Lists firewall rules (firewalld)' },
    { command: 'firewall-cmd --add-port=<port>/tcp --permanent', description: 'Opens a port in firewalld' },
    { command: 'service network restart', description: 'Restarts network services (used on older systems)' }
];
