window.pytestCommands = [
    { command: 'pytest', description: 'Runs all tests in the current directory and its subdirectories' },
    { command: 'pytest <file>', description: 'Runs tests in the specified file' },
    { command: 'pytest <directory>', description: 'Runs tests in the specified directory' },
    { command: 'pytest -v', description: 'Runs tests with verbose output' },
    { command: 'pytest -q', description: 'Runs tests with quiet output (minimal output)' },
    { command: 'pytest --maxfail=<num>', description: 'Stops testing after the specified number of failures' },
    { command: 'pytest --disable-warnings', description: 'Disables warning messages during test runs' },
    { command: 'pytest --tb=short', description: 'Shows a shorter traceback on failures' },
    { command: 'pytest --tb=lines', description: 'Shows a detailed traceback with source code lines' },
    { command: 'pytest --tb=none', description: 'Disables tracebacks on failures' },
    { command: 'pytest -k <expression>', description: 'Runs tests that match the specified expression (e.g., test names or markers)' },
    { command: 'pytest -m <marker>', description: 'Runs tests with the specified marker' },
    { command: 'pytest --marks', description: 'Lists all markers defined in the project' },
    { command: 'pytest --maxfail=1 --disable-warnings -q', description: 'Runs tests, stops after 1 failure, and suppresses warnings and output' },
    { command: 'pytest --fixtures', description: 'Lists all available fixtures' },
    { command: 'pytest --current-env', description: 'Uses the current environment variables during test execution' },
    { command: 'pytest --junitxml=<file>', description: 'Generates a JUnit XML report of the test results' },
    { command: 'pytest --html=<file>', description: 'Generates an HTML report of the test results' },
    { command: 'pytest --cov=<module>', description: 'Measures code coverage for the specified module' },
    { command: 'pytest --cov-report=html', description: 'Generates an HTML coverage report' },
    { command: 'pytest --cov-report=xml', description: 'Generates an XML coverage report' },
    { command: 'pytest --pdb', description: 'Drops into the debugger on test failure' },
    { command: 'pytest --tb=short', description: 'Shows a shortened traceback on test failures' },
    { command: 'pytest --help', description: 'Displays help information and usage for pytest commands' }
];
